name: timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
    # assets:
    # - assets/sounds/done.mp3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
